[package]
name = "gpx_simplifier"
version = "1.0.0"
edition = "2021"

[dependencies]
quick-xml = { version = "0.36.0", features = ["serialize"] }
serde = { version = "1.0.204", features = ["derive"] }

