[package]
name = "gapix_database"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
sea-orm = { version = "1.1.0", features = [ "sqlx-sqlite", "runtime-tokio-rustls", "macros", "with-chrono", "debug-print" ] }
sea-orm-migration = "1.1.2"
tracing = { workspace = true }